#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag "markusressel/py-image-dedup" "markusressel/py-image-dedup:${TRAVIS_TAG}"
docker push "markusressel/py-image-dedup:${TRAVIS_TAG}"